import Navbar from "@/components/shared/navbar/Navbar";
import { Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/footer/Footer";
import { Toaster } from "react-hot-toast";

const FigtreeFont = Figtree({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${FigtreeFont.className} h-full antialiased`}
    >
      <body>
        <Navbar />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}