import React from 'react';
import { getPrompts } from '@/lib/api/prompts';
import { FiSliders } from 'react-icons/fi';
import FilterSection from '@/components/all-prompts/FilterSection';
import PromptCard from '@/components/all-prompts/PromptCard';
import Pagination from '@/components/all-prompts/Pagination';

const AllPromptsPage = async ({ searchParams }) => {
    // Resolve searchParams object asynchronously if using Next.js 15+ 
    const resolvedParams = await searchParams;

    // Pass query arguments directly to your existing server side logic
    const page = Math.max(Number(resolvedParams?.page) || 1, 1);
    const promptResponse = await getPrompts({
        search: resolvedParams?.search || '',
        category: resolvedParams?.category || '',
        aiTool: resolvedParams?.aiTool || '',
        sort: resolvedParams?.sort || 'latest',
        page,
        limit: 6,
    });

    // The backend should return { prompts, pagination }. The fallback keeps the
    // page controls visible while the current API still returns a plain array.
    const prompts = Array.isArray(promptResponse) ? promptResponse : promptResponse?.prompts || [];
    const pagination = promptResponse?.pagination || {
        currentPage: page,
        totalPages: Math.ceil(prompts.length / 6),
        totalPrompts: prompts.length,
        limit: 6,
    };
    console.log(pagination, 'pagination');

    return (
        <div className="min-h-screen bg-[#131926] text-white pb-12 pt-[96px] px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto space-y-10 pt-12">

                {/* Header Section */}
                <div className="text-center md:text-left space-y-3">
                    <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                        Explore AI Prompts
                    </h1>
                    <p className="text-white max-w-2xl text-sm sm:text-base">
                        Discover, copy, and refine top-tier production-ready prompts generated by engineers worldwide.
                    </p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 items-start">
                    <aside className="lg:col-span-1 bg-[#161f30] p-6 rounded-2xl border border-gray-700/40 shadow-xl lg:sticky top-6">
                        <div className="flex items-center gap-2 font-bold text-lg mb-6 text-primary">
                            <FiSliders />
                            <span>Refine Prompts</span>
                        </div>
                        <FilterSection currentFilters={resolvedParams} />
                    </aside>

                    {/* Prompts Display Area */}
                    <main className="lg:col-span-3 space-y-6">
                        <div className="flex justify-between items-center bg-[#161f30] p-4 rounded-xl border border-gray-700/40">
                            <span className="text-sm font-medium text-gray-400">
                                Showing <span className="text-secondary font-bold">{prompts.length}</span> of <span className="text-secondary font-bold">{pagination?.totalPrompts ?? prompts.length}</span> amazing prompts
                            </span>
                        </div>

                        {prompts.length === 0 ? (
                            <div className="text-center py-20 bg-base-200 rounded-2xl border border-dashed border-base-content/20">
                                <p className="text-lg font-semibold text-base-content/60">No prompts found matching your criteria.</p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {prompts.map((prompt) => (
                                    <PromptCard key={prompt._id || prompt.title} prompt={prompt} />
                                ))}
                            </div>
                        )}

                        {pagination && (
                            <Pagination
                                currentPage={pagination.currentPage}
                                totalPages={pagination.totalPages}
                                filters={resolvedParams}
                            />
                        )}
                    </main>
                </div>

            </div>
        </div>
    );
};

export default AllPromptsPage;
