import React from 'react';
import { getPrompts } from '@/lib/api/prompts';
import { FiSliders } from 'react-icons/fi';
import FilterSection from '@/components/all-prompts/FilterSection';
import PromptCard from '@/components/all-prompts/PromptCard';

const AllPromptsPage = async ({ searchParams }) => {
    // Resolve searchParams object asynchronously if using Next.js 15+ 
    const resolvedParams = await searchParams;

    // Pass query arguments directly to your existing server side logic
    const prompts = await getPrompts({
        search: resolvedParams?.search || '',
        category: resolvedParams?.category || '',
        aiTool: resolvedParams?.aiTool || '',
        sort: resolvedParams?.sort || 'latest',
    }) || [];

    return (
        <div className="min-h-screen bg-base-300 text-base-content pb-12 pt-[96px] px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto space-y-10 pt-12">

                {/* Header Section */}
                <div className="text-center md:text-left space-y-3">
                    <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                        Explore AI Prompts
                    </h1>
                    <p className="text-base-content/70 max-w-2xl text-sm sm:text-base">
                        Discover, copy, and refine top-tier production-ready prompts generated by engineers worldwide.
                    </p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 items-start">
                    {/* Filter Sidebar (Client Component for interactive inputs) */}
                    <aside className="lg:col-span-1 bg-base-200 p-6 rounded-2xl border border-base-content/5 shadow-xl lg:sticky top-6">
                        <div className="flex items-center gap-2 font-bold text-lg mb-6 text-primary">
                            <FiSliders />
                            <span>Refine Prompts</span>
                        </div>
                        <FilterSection currentFilters={resolvedParams} />
                    </aside>

                    {/* Prompts Display Area */}
                    <main className="lg:col-span-3 space-y-6">
                        <div className="flex justify-between items-center bg-base-200 p-4 rounded-xl border border-base-content/5">
                            <span className="text-sm font-medium text-base-content/70">
                                Showing <span className="text-secondary font-bold">{prompts.length}</span> amazing prompts
                            </span>
                        </div>

                        {prompts.length === 0 ? (
                            <div className="text-center py-20 bg-base-200 rounded-2xl border border-dashed border-base-content/20">
                                <p className="text-lg font-semibold text-base-content/60">No prompts found matching your criteria.</p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {prompts.map((prompt) => (
                                    <PromptCard key={prompt._id || prompt.title} prompt={prompt} />
                                ))}
                            </div>
                        )}
                    </main>
                </div>

            </div>
        </div>
    );
};

export default AllPromptsPage;